group/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import GroupViewSet

router = DefaultRouter()
router.register('group', GroupViewSet)
urlpatterns = [
    path("", include(router.urls)),
]

rica_project/urls.py
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from django.urls import re_path
from django.contrib import admin
from django.urls import path, include
schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('api/v1/', include('school.urls')),
    path('api/v1/', include('group.urls')),
    path('api/v1/', include('rating.urls')),
    path('', include('webapp.urls')),
    path('', include('account.urls'))
]

webapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('student/<int:pk>', views.detail, name='detail'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete-items/', views.delete_items, name='delete_items')
]

webapp/models.py
from django.db import models

from account.models import User

school_type_choices = [('elementary', 'Начальная школа'), ('middle', 'Средняя школа'), ('high', 'Старшая школа')]


class Student(models.Model):
    name_and_family = models.TextField(max_length=300, null=False)
    date = models.DateField(null=True, default=None, verbose_name='Дата')
    phone_number = models.CharField(max_length=20)
    school_type = models.CharField(max_length=50, null=False, default='elementary', choices=school_type_choices)
    grade = models.PositiveSmallIntegerField()
    pay = models.CharField(max_length=20)
    registered = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    extra_classes = models.CharField(max_length=500)
    additional_info = models.CharField(max_length=500)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user', editable=False, null=True)

    father_name = models.TextField(max_length=300)
    father_phone = models.CharField(max_length=20)
    father_job = models.CharField(max_length=50)

    mother_name = models.TextField(max_length=300)
    mother_phone = models.CharField(max_length=20)
    mother_job = models.CharField(max_length=50)

webapp/forms.py
from django import forms
from django.forms import widgets
from .models import school_type_choices

from django.db import models

class StudentForm(forms.Form):
    name_and_family = forms.CharField(max_length=300, required=True, label="Имя и фамилия")
    date = forms.DateField(required=True, label='Дата рождения')
    phone_number = forms.CharField(max_length=20, required=True, label="Мобильный номер")
    school_type = forms.ChoiceField(choices=school_type_choices, required=True, label="Учится в ")
    grade = forms.CharField(required=True, label="Класс")
    pay = forms.CharField(required=True, label="Плата за обучение")
    registered = forms.CharField(required=True, label="Зарегестрировал")
    address = forms.CharField(required=True, label="Домашний адрес")
    extra_classes = forms.CharField(required=True, label="Кружки")
    additional_info = forms.CharField(required=True, label="Примечания")

    father_name = forms.CharField(required=True, label="Имя и фамилия отца")
    father_phone = forms.CharField(required=True, label="Контакты отца")
    father_job = forms.CharField(required=True, label="Работа отца")

    mother_name = forms.CharField(required=True, label = "Имя и фамилия матери")
    mother_phone = forms.CharField(required=True, label="Контакты матери")
    mother_job = forms.CharField(required=True, label="Работа матери")

webapp/views.py
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect, get_object_or_404
from .models import Student, school_type_choices
from .forms import StudentForm



def index(request, *args, **kwargs):
    search_querry = request.GET.get("search", "")

    if search_querry:
        students = Student.objects.filter(name_and_family__icontains=search_querry)
    else:
        students = Student.objects.all().order_by('-date')

    context = {
        'students': students
    }

    return render(request, 'index.html', context)

@login_required(login_url='login')
def new(request, *args, **kwargs):
    if request.method == 'GET':
        form = StudentForm()
        context = {
            'statuses': school_type_choices,
            'form': form
        }
        return render(request, 'new.html', context)

    elif request.method == 'POST':
        form = StudentForm(request.POST, request.FILES)
        if form.is_valid():
            Student.objects.create(
                name_and_family=form.cleaned_data['name_and_family'],
                date=form.cleaned_data['date'],
                phone_number=form.cleaned_data['phone_number'],
                school_type=form.cleaned_data['school_type'],
                grade=form.cleaned_data['grade'],
                pay=form.cleaned_data['pay'],
                registered=form.cleaned_data['registered'],
                address=form.cleaned_data['address'],
                extra_classes=form.cleaned_data['extra_classes'],
                additional_info=form.cleaned_data['additional_info'],
                father_name=form.cleaned_data['father_name'],
                father_phone=form.cleaned_data["father_phone"],
                father_job=form.cleaned_data["father_job"],
                mother_name=form.cleaned_data["mother_name"],
                mother_phone=form.cleaned_data["mother_phone"],
                mother_job=form.cleaned_data["mother_job"]
            )
            return redirect('index')
        else:
            return render(request, 'new.html', context={'form': form})


@login_required(login_url='login')
def detail(request, pk):
    student = get_object_or_404(Student, pk=pk)
    context = {
        'student': student
    }
    return render(request, 'detail.html', context)


@login_required(login_url='login')
def delete(request, pk):
    if request.method == 'GET':
        student = get_object_or_404(Student, pk=pk)
        context = {
            'student': student
        }
        return render(request, 'delete.html', context)
    else:
        student = get_object_or_404(Student, pk=pk)
        student.delete()
        return redirect('index')


@login_required(login_url='login')
def update(request, pk):
    student = get_object_or_404(Student, pk=pk)

    if request.method == 'GET':
        form = StudentForm(data={
            'name_and_family': student.name_and_family,
            'date': student.date,
            'phone_number': student.phone_number,
            'school_type': student.school_type,
            'grade': student.grade,
            'pay': student.pay,
            'registered': student.registered,
            'address': student.address,
            'extra_classes': student.extra_classes,
            'additional_info': student.additional_info,
            'father_name': student.father_name,
            'father_phone': student.father_phone,
            'father_job': student.father_job,
            'mother_name': student.mother_name,
            'mother_phone': student.mother_phone,
            'mother_job': student.mother_job
        })
        return render(request, 'edit.html', context={'form': form, 'student': student})

    if request.method == 'POST':
        form = StudentForm(data=request.POST)
        if form.is_valid():
            student.name_and_family = form.cleaned_data['name_and_family']
            student.date = form.cleaned_data['date']
            student.phone_number = form.cleaned_data['phone_number']
            student.school_type = form.cleaned_data['school_type']
            student.grade = form.cleaned_data['grade']
            student.pay = form.cleaned_data['pay']
            student.registered = form.cleaned_data["registered"]
            student.address = form.cleaned_data['address']
            student.extra_classes = form.cleaned_data['extra_classes']
            student.additional_info = form.cleaned_data['additional_info']
            student.image = form.cleaned_data['image']
            student.father_name = form.cleaned_data['father_name']
            student.father_phone = form.cleaned_data['father_phone']
            student.father_job = form.cleaned_data['father_job']
            student.mother_name = form.cleaned_data["mother_name"]
            student.mother_phone = form.cleaned_data["mother_phone"]
            student.mother_job = form.cleaned_data['mother_job']
            student.save()
            return redirect('index')
        else:
            return render(request, 'edit.html', context={'form': form, 'student': student})


@login_required(login_url='login')
def delete_items(request):
    data = request.POST
    for pk in data.keys():
        if pk == 'csrfmiddlewaretoken':
            continue
        student = get_object_or_404(Student, pk=pk)
        student.delete()
    return redirect('index')

webapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

  <div class="container">
      {% block content %}{% endblock %}
  </div>

  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
<script>
    $(document).ready(function(){
    $('select').formSelect()
    $('.datepicker').datepicker({
        format: 'yyyy-mm-dd',
        autoClose: true
    })
  });
    {% block script %}
    {% endblock %}
</script>
</body>
</html>

webapp/templates/delete.html
{% extends 'base.html' %}

{% block title %}
    Delete student {{ student.pk }}
{% endblock %}

{% block content %}
    <div class="center-align">
        <h4>Удалить ученика?</h4>
        <div class="collection">
            <a class="collection-item"><b>Имя и фамилия: </b>{{ student.name_and_family }}</a>
            <a class="collection-item"><b>Дата рождения: </b>{{ student.date }}</a>
            <a class="collection-item"><b>Номер: </b>{{ student.phone_number }}</a>
            <a class="collection-item"><b>Учится в: </b>{{ student.get_school_type_display }}</a>
        </div>
    </div>
    <div class="center-align">
        <a href="{% url 'index' %}" class="btn waves-effect waves-light deep-blue accent-3"
           style="display: inline-block">Отменить</a>
        <form action="/delete/{{ student.pk }}" method="POST" style="display: inline-block">
            {% csrf_token %}
            <button class="btn waves-effect waves-light deep-orange accent-3" type="submit"
                    style="display: inline-block">Удалить
            </button>
        </form>
    </div>
{% endblock %}

webapp/templates/detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
    <h1 class="center">Подробная информация</h1>
    <table class="centered striped highlight">
        <thead>
        <tr>
            <th>Имя и фамилия</th>
            <th>Контакт</th>
            <th>Дата рождения</th>
            <th>Школа</th>
            <th>Класс</th>
            <th>Плата за обучение</th>
            <th>Зарегестрировал</th>
            <th>Дополнительная информация</th>
            <th>Адресс</th>
        </tr>
        </thead>

        <tbody>
        <tr>
            <td>{{ student.name_and_family }}</td>
            <td>{{ student.phone_number }}</td>
            <td>{{ student.date|linebreaks }}</td>
            <td>{{ student.get_school_type_display }}</td>
            <td>{{ student.grade }}</td>
            <td>{{ student.pay }}</td>
            <td>{{ student.registered}}</td>
            <td>{{ student.additional_info }}</td>
            <td>{{ student.address }}</td>


        </tr>
        </tbody>
    </table>

<table class="centered striped highlight">
        <thead>
        <tr>
            <th>Имя и фамилия отца</th>
            <th>Телефон отца</th>
            <th>Работа отца</th>
            <th>Имя и фамилия матери</th>
            <th>Телефон матери</th>
            <th>Работа матери</th>
        </tr>
        </thead>

        <tbody>
        <tr>
            <td>{{ student.father_name }}</td>
            <td>{{ student.father_phone }}</td>
            <td>{{ student.father_job }}</td>
            <td>{{ student.mother_name }}</td>
            <td>{{ student.mother_phone }}</td>
            <td>{{ student.mother_job }}</td>


        </tr>
        </tbody>
    </table>
    <a href="{% url 'index' %}" class="waves-effect waves-light btn-small" style="margin-top: 20px; margin-left: 40%;">Вернуться на главную</a>
{% endblock %}

webapp/templates/edit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Edit student
{% endblock %}

{% block content %}
    <h1 class="center">Редактировать ученика</h1>
    <form class="col s12" action="/update/{{ student.pk }}" method="POST">

       {% include 'partial/student_form.html' with btn_text='Update' %}

    </form>
{% endblock %}

{% block script %}
    $("#id_date").addClass("datepicker");
{% endblock %}

webapp/templates/index.html
{% extends 'base.html' %}

{% block title %}Students{% endblock %}

{% block content %}
    <form class="form-inline my-2 my-lg-0" action="{% url 'index' %}">
            <input type="search" class="form-control mr-sm-2" placeholder="Введите имя" aria-label="Search" name="search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>

        </form>
        <ul>
            {% if not request.user.is_authenticated %}

            <li><a href="{% url 'register' %}" style="float:right; padding-left: 15px;">Регистрация на сайт</a></li>

            <li><a href="{% url 'login' %}" style="float:right; padding-left: 15px;">Войти</a>
            {% else %}</li>

            <li><a href="{% url 'logout' %}" style="float:right; padding-left: 15px;">Выйти</a></li>
            {% endif %}

        </ul>
        {% if messages %}
    <ul class = "messages">
        {% for message in messages %}
        <div style="background-color:yellow;" class="alert alert-success" role="alert">{{ message }}</div>
        {% endfor %}
    </ul>
    {% endif %}
    <form action="delete-items/" method="POST">
        {% csrf_token %}
        <h1 class="center">Список учеников</h1>


        <table class="centered striped highlight">
            <thead>
            <tr>
                <th><label>
                    <input id="all" class="filled-in" type="checkbox"/>
                    <span></span>
                </label></th>
                <th>Имя и фамилия</th>
                <th>Контакт</th>
                <th>Дата рождения</th>
                <th>Действия</th>
            </tr>
            </thead>
            <tbody>
            {% for student in students %}
                <td><label>
                    <input name="{{ student.pk }}" type="checkbox"/>
                    <span></span>
                </label></td>
                <td>{{ student.name_and_family }}</td>
                <td>{{ student.phone_number }}</td>
                <td>{{ student.date }}</td>
                <td>
                    <a href="{% url 'delete' student.pk %}" class="btn waves-effect waves-light deep-orange accent-3"
                       style="display: inline-block"><i class="material-icons">delete</i></a>
                    <a href="{% url 'detail' student.pk %}" class="btn waves-effect waves-light"><i class="material-icons">details</i></a>
                    <a href="{% url 'update' student.pk %}" class="btn waves-effect waves-light blue accent-4"><i
                            class="material-icons">update</i></a>
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <a href="{% url 'new' %}" class="btn-floating btn-large waves-effect waves-light red right pulse"
           style="margin-top: 20px;"><i class="material-icons">add</i></a>

        <button id="btn" class="btn waves-effect waves-light deep-orange accent-3" type="submit" disabled="disabled"
                style="display: inline-block; margin-top: 20px;">Удалить выбранные
        </button>
    </form>
{% endblock %}

{% block script %}
    $('#all').click(function(){
        if ($(this).is(':checked')){
            $('input:checkbox').prop('checked', true);
        } else {
            $('input:checkbox').prop('checked', false);
        }
    });

    $('input[type="checkbox"]').change(function(){
        if ($('input[type=checkbox]').is(":checked")) {
            $('#btn').attr('disabled', false);
        } else {
            $('#btn').attr('disabled', true);
        }
    });
{% endblock %}

webapp/templates/new.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Add new
{% endblock %}

{% block content %}
    <h1 class="center">Добавить нового ученика</h1>
    <form class="col s12" action="/new/" method="POST">

        {% include 'partial/student_form.html' with btn_text='Create' %}

    </form>
{% endblock %}

{% block script %}
    $("#id_date").addClass("datepicker");
{% endblock %}